FROM python:3.12.8-slim AS builder

COPY --from=ghcr.io/astral-sh/uv:0.8.13 /uv /bin/uv

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# geqie source
COPY geqie /geqie
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install -e /geqie --system

# app source
COPY gui /app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install -r /app/requirements/requirements_dev.txt --system

RUN python manage.py collectstatic --noinput


FROM python:3.12.8-slim AS runtime

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app /app
COPY --from=builder /geqie /geqie
COPY --from=builder /usr/local /usr/local

EXPOSE 5678
EXPOSE 8000
RUN chmod +x /app/entrypoint.sh
CMD ["/app/entrypoint.sh"]
