# Generated by Django 5.1.4 on 2025-01-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantummethod',
            name='implementation',
            field=models.TextField(default=''),
        ),
    ]
