# Generated by Django 5.1.4 on 2025-01-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quantummethod_implementation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantummethod',
            old_name='implementation',
            new_name='data',
        ),
        migrations.AddField(
            model_name='quantummethod',
            name='init',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quantummethod',
            name='map',
            field=models.TextField(default=''),
        ),
    ]
