# Generated by Django 5.1.4 on 2025-01-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_implementation_quantummethod_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantummethod',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
