# Generated by Django 5.1.4 on 2025-01-13 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_quantummethod_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantummethod',
            name='data',
        ),
        migrations.RemoveField(
            model_name='quantummethod',
            name='init',
        ),
        migrations.RemoveField(
            model_name='quantummethod',
            name='map',
        ),
        migrations.CreateModel(
            name='QuantumSubMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('init', models.TextField(default='')),
                ('map', models.TextField(default='')),
                ('data', models.TextField(default='')),
                ('quantum_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_methods', to='main.quantummethod')),
            ],
        ),
    ]
