# Generated by Django 5.1.4 on 2025-01-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_quantummethod_data_remove_quantummethod_init_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantumcomputer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quantumsubmethod',
            name='data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quantumsubmethod',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quantumsubmethod',
            name='init',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quantumsubmethod',
            name='map',
            field=models.TextField(blank=True, default=''),
        ),
    ]
