# Generated by Django 5.1.4 on 2025-01-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_quantumcomputer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantummethod',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
