# Generated by Django 5.1.4 on 2025-01-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_quantumcomputer_description_quantumsubcomputer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantumcomputer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quantumsubcomputer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
