# Generated by Django 5.1.5 on 2025-02-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_quantumcomputer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantumsubmethod',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
