# Generated by Django 5.1.5 on 2025-02-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_quantumsubmethod_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantummethod',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='quantummethod',
            name='data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quantummethod',
            name='init',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quantummethod',
            name='map',
            field=models.TextField(blank=True, default=''),
        ),
    ]
