# Generated by Django 5.1.5 on 2025-02-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_quantumsubmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantummethod',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
