# Generated by Django 5.1.5 on 2025-03-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_quantummethod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantummethod',
            name='passed_tests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quantummethod',
            name='total_tests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
