# Generated by Django 5.1.5 on 2025-03-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_quantummethod_passed_tests_quantummethod_total_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantummethod',
            name='test',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
