# Generated by Django 5.1.5 on 2025-03-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_test_result_quantummethod_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantummethod',
            name='retrieve',
            field=models.TextField(blank=True, default=''),
        ),
    ]
