# Generated by Django 5.2.4 on 2025-11-23 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_quantummethod_retrieve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=100)),
                ('shots', models.CharField(max_length=32)),
                ('is_retrieve', models.BooleanField(default=False)),
                ('input_key', models.CharField(max_length=512)),
                ('output_json_key', models.CharField(blank=True, max_length=512, null=True)),
                ('retrieved_png_key', models.CharField(blank=True, max_length=512, null=True)),
                ('original_png_key', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
